import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Save, Search, Trash2, X } from "lucide-react";
import Swal from "sweetalert2";
import { createMedidaVehiculo, deleteMedidaVehiculo, getMedidasVehiculos, updateMedidaVehiculo } from "../../api/medidasVehiculos.api";
import { obtenerUsuarioActual } from "../../utils/permisos";

const partes = [["delanteras", "Ventanas delanteras", 2], ["traseras", "Ventanas traseras", 2], ["panoramico", "Panorámico", 1], ["luneta", "Luneta", 1], ["fijos", "Fijos (opcional)", 2], ["custodias", "Custodias (opcional)", 2], ["sunroof", "Sun roof (opcional)", 1]];
const nuevo = () => ({ marca: "", modelo: "", anio: "", observaciones: "", medidas: Object.fromEntries(partes.map(([key,, cantidad]) => [key, { anchoCm: "", largoCm: "", cantidad }])) });

export default function MedidasVehiculosPage() {
  const usuario = obtenerUsuarioActual();
  const puedeEditar = ["COORDINADOR", "ADMIN", "SUPERUSUARIO"].includes(usuario?.rol);
  const puedeEliminar = ["ADMIN", "SUPERUSUARIO"].includes(usuario?.rol);
  const [registros, setRegistros] = useState([]);
  const [form, setForm] = useState(nuevo());
  const [editando, setEditando] = useState("");
  const [buscar, setBuscar] = useState("");
  const [abierto, setAbierto] = useState(false);
  const cargar = async () => { const response = await getMedidasVehiculos(); setRegistros(response.data?.data || []); };
  useEffect(() => { cargar().catch(() => Swal.fire({ icon: "error", title: "No fue posible cargar las medidas" })); }, []);
  const filtrados = useMemo(() => registros.filter((item) => `${item.marca} ${item.modelo} ${item.anio}`.toLowerCase().includes(buscar.toLowerCase())), [registros, buscar]);
  const cambiarMedida = (parte, campo, value) => setForm((actual) => ({ ...actual, medidas: { ...actual.medidas, [parte]: { ...actual.medidas[parte], [campo]: value } } }));
  const guardar = async () => { try { if (!form.marca.trim() || !form.modelo.trim()) return Swal.fire({ icon: "warning", title: "Ingrese marca y modelo" }); editando ? await updateMedidaVehiculo(editando, form) : await createMedidaVehiculo(form); await cargar(); setForm(nuevo()); setEditando(""); setAbierto(false); Swal.fire({ icon: "success", title: "Medidas guardadas", timer: 1400, showConfirmButton: false }); } catch (error) { Swal.fire({ icon: "error", title: "No fue posible guardar", text: error.response?.data?.message }); } };
  const editar = (item) => { setForm({ ...nuevo(), ...item, medidas: { ...nuevo().medidas, ...(item.medidas || {}) } }); setEditando(item._id); setAbierto(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const eliminar = async (item) => { const result = await Swal.fire({ icon: "warning", title: "¿Eliminar estas medidas?", text: `${item.marca} ${item.modelo}`, showCancelButton: true, confirmButtonText: "Eliminar", confirmButtonColor: "#dc2626" }); if (result.isConfirmed) { await deleteMedidaVehiculo(item._id); await cargar(); } };
  return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5 shadow-sm"><div><h1 className="text-xl font-black text-slate-900">Medidas de vehículos</h1><p className="text-sm text-slate-500">Catálogo reutilizable de vidrios por marca y modelo.</p></div>{puedeEditar && <button onClick={() => { setForm(nuevo()); setEditando(""); setAbierto(true); }} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-bold text-white"><Plus size={18} /> Agregar vehículo</button>}</header>
  {abierto && puedeEditar && <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-black">{editando ? "Editar medidas" : "Nueva ficha de medidas"}</h2><button onClick={() => setAbierto(false)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X /></button></div><div className="grid gap-3 md:grid-cols-3"><Campo label="Marca" value={form.marca} onChange={(value) => setForm({ ...form, marca: value.toUpperCase() })} /><Campo label="Modelo / referencia" value={form.modelo} onChange={(value) => setForm({ ...form, modelo: value.toUpperCase() })} /><Campo label="Año (opcional)" value={form.anio} onChange={(value) => setForm({ ...form, anio: value.replace(/\D/g, "").slice(0, 4) })} /></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{partes.map(([key, label]) => <div key={key} className="rounded-xl border bg-slate-50 p-3"><p className="mb-2 text-sm font-bold text-slate-700">{label}</p><div className="grid grid-cols-3 gap-2"><Campo label="Ancho cm" type="number" value={form.medidas[key]?.anchoCm} onChange={(value) => cambiarMedida(key, "anchoCm", value)} /><Campo label="Largo cm" type="number" value={form.medidas[key]?.largoCm} onChange={(value) => cambiarMedida(key, "largoCm", value)} /><Campo label="Cantidad" type="number" value={form.medidas[key]?.cantidad} onChange={(value) => cambiarMedida(key, "cantidad", value)} /></div></div>)}</div><textarea value={form.observaciones} onChange={(event) => setForm({ ...form, observaciones: event.target.value.toUpperCase() })} placeholder="Observaciones o tolerancias" className="mt-4 w-full rounded-xl border p-3" /><button onClick={guardar} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><Save size={18} /> Guardar medidas</button></section>}
  <section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={buscar} onChange={(event) => setBuscar(event.target.value)} placeholder="Buscar marca, modelo o año" className="w-full rounded-xl border py-2.5 pl-10 pr-3" /></div></div><div className="divide-y">{filtrados.map((item) => <div key={item._id} className="flex flex-wrap items-start justify-between gap-3 p-4"><div><p className="font-black text-slate-900">{item.marca} {item.modelo} {item.anio}</p><div className="mt-2 flex flex-wrap gap-2">{partes.map(([key, label]) => { const medida = item.medidas?.[key]; return Number(medida?.anchoCm) > 0 && Number(medida?.largoCm) > 0 ? <span key={key} className="rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-600">{label}: {medida.anchoCm} × {medida.largoCm} cm ({medida.cantidad})</span> : null; })}</div></div><div className="flex gap-2">{puedeEditar && <button onClick={() => editar(item)} title="Editar" className="rounded-lg border p-2 text-blue-700"><Pencil size={16} /></button>}{puedeEliminar && <button onClick={() => eliminar(item)} title="Eliminar" className="rounded-lg border p-2 text-red-700"><Trash2 size={16} /></button>}</div></div>)}{!filtrados.length && <p className="p-10 text-center text-slate-500">No hay medidas registradas.</p>}</div></section></div>;
}

function Campo({ label, value, onChange, type = "text" }) { return <label className="text-xs font-bold uppercase text-slate-500">{label}<input type={type} min={type === "number" ? 0 : undefined} value={value ?? ""} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 text-sm font-normal text-slate-800" /></label>; }
